[tools]
buf = "latest"
go = "latest"
golangci-lint = "latest"
protobuf = "latest"

[tasks."generate"]
depends = ["generate:*"]

[tasks."generate:buf"]
run = "buf generate"

[tasks."generate:crd"]
file = "hack/update-codegen.sh"

[tasks."lint"]
depends = ["lint:*"]

[tasks."lint:go"]
run = "golangci-lint run"

[tasks."lint:buf"]
run = "buf lint"
