apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: tlscert
type: Opaque
stringData:
  api-token: "PLACEHOLDER"
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: local-testing@tlscert.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token